#!/bin/sh

cd $BACKUP_DIR

INC_FILE=/tmp/backup_files
INC_FILE_IGNORE="$INC_FILE"_with_ignore
INC_FILE_EXCLUDE="$INC_FILE"_exclude

fd -H -I --full-path . > $INC_FILE_IGNORE
fd -H --full-path . > $INC_FILE

cat $INC_FILE $INC_FILE_IGNORE | sort | uniq -u > $INC_FILE_EXCLUDE

restic backup --exclude-file=$INC_FILE_EXCLUDE ./

